SELECT  PRODUCT_CODE, (SUM(sales_amount) * PRICE) as SALES
FROM PRODUCT
JOIN OFFLINE_SALE
ON PRODUCT.product_id = OFFLINE_SALE.product_id
GROUP BY OFFLINE_SALE.product_id
ORDER BY SALES DESC, PRODUCT_CODE ASC