SELECT b.CATEGORY, SUM(SALES) "TOTAL_SALES"
FROM BOOK b
INNER JOIN BOOK_SALES bs ON b.BOOK_ID = bs.BOOK_ID
WHERE sales_date between '2022-01-01' AND '2022-01-31'
GROUP BY CATEGORY
ORDER BY CATEGORY ASC